resilience4j:
  ratelimiter:
    instances:
      AuthController:
        limit-for-period: 3
        limit-refresh-period: 10s
        timeout-duration: 3m
      CategoryController:
        limit-for-period: 3
        limit-refresh-period: 30s
        timeout-duration: 1m
      RoomController:
        limit-for-period: 4
        limit-refresh-period: 30s
        timeout-duration: 1m
      EmailController:
        limit-for-period: 3
        limit-refresh-period: 30s
        timeout-duration: 3m